#!/usr/bin/env bash

# Starts a Tetris game in a Java Swing GUI.
# Run this from the base project directory.
# echo "#: '$#'"
if [ "$#" -gt '0' ]; then
    # echo "arg1: '$1'"
    if [ "$1" = '--rebuild' ]; then
        echo 'Rebuilding...'

        ./mvnw package -f tetris/pom-tetris.xml && java -jar tetris/target/tetris-1.0.0.jar
        exit 0
    fi
fi

java -jar tetris/target/tetris-1.0.0.jar
