name: Publish package to GitHub Packages
on:
  push:
    tags: ['v**']
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install root pom
        run: ./mvnw install
      - name: Publish package
        run: ./mvnw -B deploy -f pom-lib.xml
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
