name: Publish package to GitHub Packages
on:
  push:
    tags: ['v**']
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish package
        run: |
          # If tag is "v.X.X.X" only, deploy everything.
          if [[ "$TAG_NAME" =~ v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Deploying all modules";
            ./mvnw -B deploy;

          # If tag is "v.X.X.X-modulename..."
          elif [[ "$TAG_NAME" =~ v[0-9]+\.[0-9]+\.[0-9]+\-[a-z]+ ]]; then
            VALID_MODULES=(bucket tetris sudoku);
            MODULE=$(echo "$TAG_NAME" | cut -d '-' -f 2);
            mod_found=false;

            # Try to match against hard-coded list of current modules.
            for valid_mod in "$VALID_MODULES[@]"; do
              if [ "$valid_mod" = "$MODULE" ]; then
                mod_found=true;
                echo "Deploying module: $MODULE";
                ./mvnw -B deploy -pl "$MODULE";
                break;
              fi
            done

            if [ "$mod_found" = false ]; then
              echo "MALFORMED TAG OR UNRECOGNIZED MODULE: $MODULE"
            fi
          else
            echo "MALFORMED TAG: $TAG_NAME"
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
