name: Publish package to GitHub Packages
on:
  push:
    tags: ['v**']
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish package
        run: |
          SUBMODULE=$(echo "$TAG_NAME" | cut -d '-' -f 2)
          if [ -n "$SUBMODULE" ]; then
            echo "Deploying submodule $SUBMODULE"
            ./mvnw -B deploy -pl "$SUBMODULE"
          else
            echo "Deploying all modules"
            ./mvnw -B deploy
          fi
        env:
          TAG_NAME: ${{ github.ref_name }}
